---
plugin: aws_ec2
boto_profile: default
regions:
  - eu-west-1
filters:
  instance-state-name: "running"
  #tag:Environment:
   # - dev
hostnames:
  - tag:Name
  - ip-address
  - public-ip-address
  #- dns-name
strict permission: False
compose:
  ansible_host: public_ip_address 
 # ansible_host:  private_ip_address
