---
# vars file for web
docker_py_deps:
  - "python-dev"
ansible_python_interpreter: /usr/bin/python3
#remote_user: ubuntu
docker_group: docker
docker_remote_app_dir: /tmp/helloworld
ansible_host: "{{ public_ip_address }}"