version: '3'
 
services:
    nginx_img:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx_con
        build:
            context: ./dev_app
        networks:
            public_net:
                ipv4_address: ${NGINX_IP}
 
