---
- hosts: all
  gather_facts: no
  vars:  
    ansible_user: ubuntu 
    ansible_ssh_private_key_file: 
  
  tasks:
  - name: create build directory
    debug:
     msg:  "{{ public_ip_address }}"

  - name: create build directory
    file:
        path: /tmp/developer_code
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
