---
- hosts: all
  gather_facts: no
  vars:  
   ansible_user: ubuntu 
   ansible_ssh_private_key_file: ""
   ansible_python_interpreter: /usr/bin/python3

#- name: apply nginx configuration 
 # hosts: map_blue_Server
 # vars:
 #  ansible_host: "{{ public_ip_address }}"
 #  ansible_user: ubuntu
 # become: true

  #roles:
  #  - nginx
 #pre_tasks:
    #- name: update apt cache if needed
     # become: yes
   #   apt:
       # update_cache=yes
       #cache_valid_time=3600
        
- name: apply redis configuration 
  hosts: map_blue_Server
  vars:
    ansible_host: "{{ public_ip_address }}"
    ansible_user: ubuntu
  become: true
  
  roles:
   #- redis 

- name: apply and build developer code into docker and configure
  hosts: map_blue_Server
  vars:
    - ansible_host: "{{ public_ip_address }}"
    - ansible_user: ubuntu
  become: yes
  roles:
   # - app
  tasks:
    - name: "state docoker app"
      shell: "docker run -d -p 82:80 --name myvoting -e REDIS_PORT=6379 -e REDIS_PWD={{ redis_password }}  -e REDIS={{ ansible_host }} --name awogavotingapp seunvotingapp:v1"
        
- name: Build prometheus and grafana dashboard configuration 
  hosts: map_blue_Server
  vars:
    ansible_host: "{{ public_ip_address }}"
    ansible_user: ubuntu
  become: true
 